---
- name: update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == "Debian"

- name: install deps (Ubuntu)
  apt: >
    pkg={{item}}
    state=installed
  with_items:
    - unzip
    - jq
  when: ansible_os_family == "Debian"

- name: install deps (RHEL)
  yum: >
    pkg={{item}}
    state=installed
  with_items:
    - unzip
    - jq
  when: ansible_os_family == "RedHat"

- name: download consul
  get_url: >
    url={{consul_download}}
    dest={{consul_download_folder}}
  register: consul_was_downloaded

- name: create consul directory
  file: >
    state=directory
    path={{ item }}
  with_items:
    - "{{ consul_home }}"
    - "{{ consul_home }}/data"
    - "{{ consul_home }}/bin"
    - "{{ consul_config_dir }}"

- name: copy and unpack
  unarchive: >
    src={{ consul_download_folder }}/{{ consul_archive }}
    dest={{ consul_home }}/bin
    copy=no
  when: consul_was_downloaded|changed

- name: create consul group
  group: >
    name={{consul_group}}
    state=present

- name: create consul user
  user: >
    name={{consul_user}}
    group={{consul_group}}

- name: set ownership
  file: >
    state=directory
    path={{consul_home}}
    owner={{consul_user}}
    group={{consul_group}}
    recurse=yes

- name: copy consul upstart script
  template: >
    src=consul.conf.j2
    dest=/etc/init/consul.conf
    owner={{consul_user}}
    group={{consul_group}}
    mode=0755

- name: add consul to path through profile.d
  template: >
    src=consul.sh.j2
    dest=/etc/profile.d/consul.sh
    owner=root
    group=root
    mode=0755

- name: copy consulkv script
  template: >
    src=consulkv.j2
    dest={{consul_home}}/bin/consulkv
    owner={{consul_user}}
    group={{consul_group}}
    mode=0755

- name: consul config file
  template: >
    src=consul.json.j2
    dest={{ consul_config_file }}
    owner={{consul_user}}
    group={{consul_group}}
    mode=0755
