---
- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart consul
  action: service name=consul state=restarted enabled=yes
  when: consul_manage_service

- name: reload consul config
  become: yes
  command: pkill -1 consul
  when: consul_service_state is not "stopped" and consul_manage_service

- name: restart dnsmasq
  service: name=dnsmasq state=restarted enabled=yes

# Need to override handler defined in both franklinkim.nginx and geerlingguy.nginx
# because Ansible arbitrarily picks one handler to run and the franklinkim.nginx
# handler has a state guard that will not be defined on RedHat systems
- name: consul reload nginx
  service: name=nginx state=reloaded
